version: "3.9"

services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    command:
      - sh -c "python manage.py migrate && gunicorn YoutubeBot.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - database
    environment:
      - DEBUG=false
      - ALLOWED_HOSTS=*
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
    restart: always

  nginx:
    container_name: nginx
    command:
      - nginx -g 'daemon off;'
    image: nginx:latest
    depends_on:
      - app
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  main:

volumes:
  postgres: