# Generated by Django 4.2 on 2023-05-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subscriber', models.IntegerField(default=0)),
                ('link', models.URLField()),
                ('keyword', models.CharField(max_length=50)),
            ],
        ),
    ]
